#!/usr/bin/env python3
"""
AeroJudge PCB 3.61+ TS43 thumbwheel volume service.

Installed path: /var/opt/volume_service/volume.py

The AeroJudge PCB 3.61+ routes the Same Sky TS43 thumbwheel contacts through
Linux gpio-key overlays. This daemon listens for the resulting evdev key
events and controls the PCM5122 hardware mixer with amixer.

GPIO pin assignments live in /boot/config.txt. This file only depends on the
keycodes generated by those overlays.
"""

import atexit
import os
import re
import selectors
import signal
import subprocess
import sys
import threading
import time
from dataclasses import dataclass
from typing import Dict, Iterable, Optional, Set

try:
    import evdev
except ImportError as exc:
    print("python3-evdev is required. Install with: sudo apt install python3-evdev", file=sys.stderr)
    raise SystemExit(1) from exc


DEBUG = False

# Keycodes must match /boot/config.txt gpio-key overlays.
KEY_VOL_DOWN = 114       # KEY_VOLUMEDOWN
KEY_VOL_DOWN_FAST = 159  # KEY_FORWARD, used as AeroJudge down-fast modifier
KEY_VOL_UP = 115         # KEY_VOLUMEUP
KEY_VOL_UP_FAST = 160    # KEY_CLOSECD, used as AeroJudge up-fast modifier
KEY_MUTE = 113           # KEY_MUTE

TARGET_KEYS = {
    KEY_VOL_DOWN,
    KEY_VOL_DOWN_FAST,
    KEY_VOL_UP,
    KEY_VOL_UP_FAST,
    KEY_MUTE,
}
DIRECTION_KEYS = {KEY_VOL_DOWN, KEY_VOL_UP}

ALSA_CARD = "sndrpihifiberry"
MIXER_CONTROL = "Digital"
FEEDBACK_DEVICE = "pulse"

VOLUME_MIN = 65
VOLUME_MAX = 100
VOLUME_STEP_SLOW = 1
VOLUME_STEP_FAST = 3

REPEAT_DELAY = 0.4
REPEAT_INTERVAL = 0.15
DEVICE_WAIT_TIMEOUT = 30
DEVICE_RETRY_INTERVAL = 1
MIXER_WAIT_TIMEOUT = 30
MIXER_RETRY_INTERVAL = 1

BEEP_ENABLED = True
BEEP_MIN_INTERVAL = 0.04
BEEP_WARNING_INTERVAL = 30
SERVICE_DIR = os.path.dirname(os.path.abspath(__file__))
TONE_UP_FILE = os.path.join(SERVICE_DIR, "tone-up.wav")
TONE_DOWN_FILE = os.path.join(SERVICE_DIR, "tone-down.wav")


def debug(message: str) -> None:
    if DEBUG:
        print(message, flush=True)


class VolumeError(Exception):
    """Raised when ALSA volume state cannot be read or changed."""


@dataclass
class MixerState:
    volume: int
    muted: bool


class Volume:
    def __init__(self) -> None:
        state = self._get_initial_state()
        self.volume = state.volume
        self.muted = state.muted
        self.last_volume = state.volume
        print(f"Using ALSA card/control: {ALSA_CARD}/{MIXER_CONTROL}", flush=True)

    def change(self, delta: int) -> int:
        if self.muted:
            self.unmute()

        next_volume = self._clamp(self.volume + delta)
        return self.set_volume(next_volume)

    def set_volume(self, volume: int) -> int:
        volume = self._clamp(volume)
        self._run_amixer("set", MIXER_CONTROL, "unmute", f"{volume}%")
        state = self.get_state()
        self.volume = state.volume
        self.muted = state.muted
        if not self.muted:
            self.last_volume = self.volume
        debug(f"Volume set to {self.volume}%, muted={self.muted}")
        return self.volume

    def toggle_mute(self) -> bool:
        if self.muted:
            self.unmute()
            self.set_volume(self.last_volume)
        else:
            self.last_volume = self.volume
            self._run_amixer("set", MIXER_CONTROL, "mute")
            state = self.get_state()
            self.volume = state.volume
            self.muted = state.muted
        debug(f"Mute toggled, muted={self.muted}, volume={self.volume}%")
        return self.muted

    def unmute(self) -> None:
        self._run_amixer("set", MIXER_CONTROL, "unmute")
        state = self.get_state()
        self.volume = state.volume
        self.muted = state.muted

    def get_state(self) -> MixerState:
        output = self._run_amixer("get", MIXER_CONTROL)
        return self._parse_amixer_state(output)

    def _run_amixer(self, *args: str) -> str:
        command = ["amixer", "-c", ALSA_CARD, *args]
        result = subprocess.run(command, capture_output=True, text=True, check=False)
        if result.returncode != 0:
            message = result.stderr.strip() or result.stdout.strip() or "unknown amixer error"
            raise VolumeError(f"{' '.join(command)} failed: {message}")
        return result.stdout

    def _get_initial_state(self) -> MixerState:
        deadline = time.monotonic() + MIXER_WAIT_TIMEOUT
        while True:
            try:
                return self.get_state()
            except VolumeError as exc:
                if time.monotonic() >= deadline:
                    raise
                print(f"Waiting for ALSA mixer {MIXER_CONTROL!r}: {exc}", file=sys.stderr, flush=True)
                time.sleep(MIXER_RETRY_INTERVAL)

    def _parse_amixer_state(self, output: str) -> MixerState:
        lines = [line for line in output.splitlines() if "%" in line]
        if not lines:
            raise VolumeError(f"Unable to parse amixer output for {MIXER_CONTROL!r}")

        line = lines[-1]
        percent_matches = re.findall(r"\[(\d{1,3})%\]", line)
        state_matches = re.findall(r"\[(on|off)\]", line)
        if not percent_matches:
            raise VolumeError(f"Unable to parse volume percentage from: {line}")

        volume = self._clamp(int(percent_matches[-1]))
        muted = bool(state_matches and state_matches[-1] == "off")
        return MixerState(volume=volume, muted=muted)

    def _clamp(self, volume: int) -> int:
        return max(VOLUME_MIN, min(VOLUME_MAX, volume))


class TonePlayer:
    def __init__(self) -> None:
        self.lock = threading.Lock()
        self.last_started = 0.0
        self.last_warning: Dict[str, float] = {}

    def up(self) -> None:
        self._play(TONE_UP_FILE)

    def down(self) -> None:
        self._play(TONE_DOWN_FILE)

    def _play(self, tone_file: str) -> None:
        if not BEEP_ENABLED:
            return

        if not os.path.exists(tone_file):
            self._warn(tone_file, f"Tone file not found: {tone_file}")
            return

        now = time.monotonic()
        with self.lock:
            if now - self.last_started < BEEP_MIN_INTERVAL:
                return
            self.last_started = now

        thread = threading.Thread(target=self._play_async, args=(tone_file,), daemon=True)
        thread.start()

    def _play_async(self, tone_file: str) -> None:
        result = subprocess.run(
            ["aplay", "-q", "-D", FEEDBACK_DEVICE, tone_file],
            capture_output=True,
            text=True,
            check=False,
        )
        if result.returncode != 0:
            message = result.stderr.strip() or result.stdout.strip() or "unknown aplay error"
            self._warn(tone_file, f"aplay failed for {tone_file}: {message}")

    def _warn(self, tone_file: str, message: str) -> None:
        now = time.monotonic()
        with self.lock:
            if now - self.last_warning.get(tone_file, 0.0) < BEEP_WARNING_INTERVAL:
                return
            self.last_warning[tone_file] = now
        print(message, file=sys.stderr, flush=True)


class ThumbwheelService:
    def __init__(self) -> None:
        self.volume = Volume()
        self.tones = TonePlayer()
        self.held_keys: Set[int] = set()
        self.selector = selectors.DefaultSelector()
        self.devices: Dict[int, evdev.InputDevice] = {}
        self.repeat_timer: Optional[threading.Timer] = None
        self.lock = threading.RLock()
        self.running = True

    def run(self) -> None:
        self._open_devices_with_retry()
        debug(f"Initial volume: {self.volume.volume}%, muted={self.volume.muted}")

        while self.running:
            for key, _ in self.selector.select(timeout=1):
                device = key.fileobj
                try:
                    for event in device.read():
                        self._handle_event(event)
                except OSError as exc:
                    print(f"Input device read failed: {exc}", file=sys.stderr)

    def stop(self) -> None:
        self.running = False
        self._cancel_repeat()
        for device in self.devices.values():
            try:
                self.selector.unregister(device)
            except Exception:
                pass
            try:
                device.ungrab()
            except OSError:
                pass
            device.close()
        self.devices.clear()

    def _open_devices_with_retry(self) -> None:
        deadline = time.monotonic() + DEVICE_WAIT_TIMEOUT
        while self.running:
            devices = list(find_volume_devices())
            if devices:
                for device in devices:
                    try:
                        device.grab()
                    except OSError as exc:
                        device.close()
                        raise RuntimeError(f"Unable to grab volume input device {device.path}: {exc}") from exc
                    self.selector.register(device, selectors.EVENT_READ)
                    self.devices[device.fd] = device
                    print(f"Monitoring volume input device: {device.path} {device.name}", flush=True)
                return

            if time.monotonic() >= deadline:
                raise RuntimeError("No input devices found for AeroJudge volume keycodes")

            print("Waiting for AeroJudge volume input devices...", file=sys.stderr)
            time.sleep(DEVICE_RETRY_INTERVAL)

    def _handle_event(self, event: evdev.InputEvent) -> None:
        if event.type != evdev.ecodes.EV_KEY:
            return

        keycode = event.code
        if keycode not in TARGET_KEYS:
            return

        # Kernel auto-repeat is intentionally ignored; this service owns repeat timing.
        if event.value == 2:
            return

        with self.lock:
            if event.value == 1:
                self.held_keys.add(keycode)
                debug(f"Pressed {keycode}, held={sorted(self.held_keys)}")
                self._handle_press(keycode)
            elif event.value == 0:
                self.held_keys.discard(keycode)
                debug(f"Released {keycode}, held={sorted(self.held_keys)}")
                if not self._direction_key_held():
                    self._cancel_repeat()

    def _handle_press(self, keycode: int) -> None:
        if keycode == KEY_MUTE:
            self.volume.toggle_mute()
            return

        if keycode in DIRECTION_KEYS:
            self._apply_direction_step()
            self._schedule_repeat(REPEAT_DELAY)
        elif keycode in {KEY_VOL_DOWN_FAST, KEY_VOL_UP_FAST} and self._direction_key_held():
            debug("Fast modifier pressed while direction is held")

    def _apply_direction_step(self) -> None:
        delta = self._current_delta()
        if delta == 0:
            return

        try:
            before = self.volume.volume
            volume = self.volume.change(delta)
            self._play_feedback(delta, before, volume)
            debug(f"Applied delta {delta}, volume now {volume}%")
        except VolumeError as exc:
            print(str(exc), file=sys.stderr)

    def _play_feedback(self, delta: int, before: int, after: int) -> None:
        if delta > 0:
            self.tones.up()
        else:
            self.tones.down()

    def _current_delta(self) -> int:
        if KEY_VOL_DOWN in self.held_keys:
            step = VOLUME_STEP_FAST if KEY_VOL_DOWN_FAST in self.held_keys else VOLUME_STEP_SLOW
            return -step
        if KEY_VOL_UP in self.held_keys:
            step = VOLUME_STEP_FAST if KEY_VOL_UP_FAST in self.held_keys else VOLUME_STEP_SLOW
            return step
        return 0

    def _direction_key_held(self) -> bool:
        return bool(self.held_keys & DIRECTION_KEYS)

    def _schedule_repeat(self, delay: float) -> None:
        self._cancel_repeat()
        self.repeat_timer = threading.Timer(delay, self._repeat)
        self.repeat_timer.daemon = True
        self.repeat_timer.start()

    def _repeat(self) -> None:
        with self.lock:
            if not self.running or not self._direction_key_held():
                self.repeat_timer = None
                return

            self._apply_direction_step()
            self.repeat_timer = threading.Timer(REPEAT_INTERVAL, self._repeat)
            self.repeat_timer.daemon = True
            self.repeat_timer.start()

    def _cancel_repeat(self) -> None:
        if self.repeat_timer:
            self.repeat_timer.cancel()
            self.repeat_timer = None


def find_volume_devices() -> Iterable[evdev.InputDevice]:
    for path in evdev.list_devices():
        try:
            device = evdev.InputDevice(path)
            key_caps = device.capabilities().get(evdev.ecodes.EV_KEY, [])
            if is_gpio_key_device(device) and any(key in key_caps for key in TARGET_KEYS):
                yield device
            else:
                device.close()
        except OSError as exc:
            print(f"Unable to inspect input device {path}: {exc}", file=sys.stderr)


def is_gpio_key_device(device: evdev.InputDevice) -> bool:
    return device.name.startswith("button@")


def main() -> int:
    try:
        service = ThumbwheelService()
    except VolumeError as exc:
        print(str(exc), file=sys.stderr)
        return 1

    def shutdown(_signum=None, _frame=None) -> None:
        service.stop()

    signal.signal(signal.SIGINT, shutdown)
    signal.signal(signal.SIGTERM, shutdown)
    atexit.register(service.stop)

    try:
        service.run()
    except (RuntimeError, VolumeError) as exc:
        print(str(exc), file=sys.stderr)
        return 1

    return 0


if __name__ == "__main__":
    sys.exit(main())
